- title: Vehicle Servicing
  sub: Duration varies • From £140.00
  description: >-
    12 point check

- title: MoT Testing
  sub: 45 minutes • £50
  description: Mandatory vehicle annual test.

- title: Spares & Repairs
  sub: Duration varies • Varies according to parts
  description: Parts for all cars and light commercials

- title: Shock absorbers
  sub: 30 minutes • Varies
  description: Supply and fit also parts supplied

- title: Welding
  sub: Duration varies • Varies
  description: Welding to Mot test specification

- title: Exhausts
  sub: Price varies
  description:

- title: Tyre supply & Fitting
  sub: Duration varies • From £34.99
  description: Tyre, valve, fitting & balancing

- title: Vehicle diagnostics
  sub: 30 minutes • From £35
  description: Diagnostics and analysis
